### ISSUE TITLE
Mechanism to read the test output directory by browser, language and case

### ISSUE THREAD

**Issue by sqlkamal** [Traap/amber#43]
![outputdir](https://user-images.githubusercontent.com/33817562/37303822-a423abf2-25fd-11e8-88e3-388f97d41121.PNG)

**Comment by Traap** [comment]
new command line options:

- --language=[da, de, en, es, fr-ca, fr-eu, ge, it, na, no]
- -- browser=[Chrome, Firefox, IE]
- -- dump
