### ISSUE TITLE
Generalized Template method for adding Attributes like Browser, Language, PageName for processing by amber

### ISSUE THREAD

**Issue by NathanBockrath** [Traap/amber#48]
We added a second test-output factory generation technique to amber to support directories for browser and language defined by parameters, which for the purposes of discussion I will call "attributes". This issue is an enhancement which must allow these attributes to be defined in a general sense, as part of the YAML input to amber.  This way, future variants of the system could define attributes in the YAML at the plan level in a way that is meaningful as part of the output report. 

As an example, let us suppose that the test report must be generated for each browser and language on a list of supported client OS, must have the full test plan run.  Then, we would want to add an client_OS attribute to the list of attributes and create another level of sub-directories for it.

**Comment by Traap** [comment]
This is an interesting idea.  Can you provide "attributes" examples?

**Comment by NathanBockrath** [comment]
There is the client OS case, I mentioned above; Also tiering could be considered a case for DXT ( oneTier vs twoTier ),  or Database version (MySQL vs Postgres SQL vs NoSQL) which we might want to handle the same way.  
I'm thinking about what amber would do in a case  where we have the following directory structure:
attributeList:  [ attribute1, attribute2, ... , attributeN ] 
/factory/
    /plan
    /suite
    /case
    /attribute1/
          /plan
          /suite 
          /case
         /attribute2
               /plan
               /suite
               /case?
 If the plan directory exists at the factory level would that plan still be incorporated in the output?  It seems like this would allow specific tests for specific attributes and common tests for all attributes.  
What happens with any extra attributes?

**Comment by Traap** [comment]
Suspend this topic.
