### ISSUE TITLE
Add an option(parameter) to pass the build & execution path from amber to yaml to gradle to java

### ISSUE THREAD

**Issue by sqlkamal** [Traap/amber#56]

**Comment by sqlkamal** [comment]
Add an option in options.rb to pass the build-execution path

**Comment by Traap** [comment]
File.expand_path(filename) added to YAML argument token.

**Comment by NathanBockrath** [comment]
We observed when running amber 0.0.125, that the environmental substitutions are mangling the order in the output files. the yaml and the output tex file are attached.

Input Yaml:

case:
  name: ${file}

  purpose: >
    This test case is used to demonstrate the ${file} page has been translated to
    ${language} correctly.

  requirement: IUR-001

  steps:
    - confirm: All text objects have correct ${language} translations. 
      expectation: >
        All textual inspections are correct, user interface screens are
        captured, and subsutions for [${file}, ${language}, ${browser}, ${language-code}]
        are accurate.
      sudo: false
      command: gradle 
      argument: > 
         -p 
         /c/Users/nbockrath.FENWAL/git/ui-automation-centerium 
         test 
         --tests *${file} 
         -Dbrowser=${browser} 
         -Dlanguage=${language-code}
         
      evidence: Starts on next line.


Output About.tex:

`\subsection{Test Case: About}
\begin{description}[align=right,leftmargin=*,labelindent=3cm]
\item[Purpose:] This test case is used to demonstrate the About page has been translated to English correctly.

\item[Requirement:] IUR-001
\end{description}
\begin{lstlisting}[numbers=left]
       Step: 1
    Confirm: All text objects have correct English translations.
Expectation: All textual inspections are correct, user interface screens are captured, and subsutions for [About, English, Chrome, en] are accurate.

    Command: gradle C:/Users/nbockrath.FENWAL/git/ui-automation-centerium/report/-p /c/Users/nbockrath.FENWAL/git/ui-automation-centerium test --tests *About -Dbrowser=Chrome -Dlanguage=en
Test Result: FAIL
   Evidence: Starts on next line.

FAILURE: Build failed with an exception.

* What went wrong:
Project 'C' not found in root project 'tmp'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

\end{lstlisting}
`

**Comment by Traap** [comment]
${home} is replaced by ~.  ~ is expanded to user home directory.   

[substitute.yaml](https://github.com/Traap/amber/blob/master/factory/case/substitute/substitute.yaml) has a contrived example of ${file}, ${language}, ${browser}, ${language-code}, ${home} being substituted.
