### ISSUE TITLE
amber only runs the first case in freshly cloned/checked out repositories

### ISSUE THREAD

**Issue by NathanBockrath** [Traap/amber#65]
amber seems to hang after the first case runs on a new repository or branch; a second attempt will run all the way through.  What kind of logs would give insight into the issue?

**Comment by Traap** [comment]
I have not been able to reproduce this issue with my OXS, Windows 10 with Windows Subsystem for Linux enabled, or Cygwin on Windows 7.

**Comment by NathanBockrath** [comment]
We have Anna's  Win7 machine in this state right now, when trying to build tool-validation/git-client  plan command-line .  Do you have time to look at it?

**Comment by Traap** [comment]
This is not a bug with Amber.  Anna's computer was set up correctly.  A person **MUST** be a contributor GitHub.com/Traap/quicksort repository in order to run the git-client tool-validation protocol.  The person running the validation **MUST** be a contributor so **git push** works.
